### ISSUE TITLE
Resolve merge conflict

### ISSUE THREAD

**Issue by nichtich** [wikicite/bibtag2018#6]
Edits in branch <https://github.com/wikicite/bibtag2018/tree/merge-conflict>. Git is not that good for parallel working on the same document. I'll try to include my lost changes tomorrow.

**Comment by zuphilip** [comment]
Let me know whether I can help you with this... BTW the same would happen, when we worked with one Powerpoint file.

**Comment by zuphilip** [comment]
@nichtich How did you solve this issue? I don't see any recent changes on GitHub...
